# Stage 1, based on Node.js, to build and compile React
FROM node:18 as builder

# Create app directory
WORKDIR /app

# Clone/Pull Source code to app directory
COPY frontend/package*.json ./

# Install app dependencies
RUN npm install

# Copy frontend source files
COPY frontend/ .

# Build your frontend
RUN npm run build

# Stage 2, based on Nginx, to have only the compiled app, ready for production with Nginx
FROM nginx:alpine

# Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

# Copy static build directory from builder stage
COPY --from=builder /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Container start command
CMD ["nginx", "-g", "daemon off;"]
