services:
  migrations:
    image: migrations-image
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  api:
    image: api-image
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      GRPC_SERVER_PORT: ${GRPC_SERVER_PORT}
      TOKEN_SYMMETRIC_KEY: ${TOKEN_SYMMETRIC_KEY}
      ENVIRONMENT: ${ENVIRONMENT}
      SENDINBLUE_API_KEY: ${SENDINBLUE_API_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
    depends_on:
      - db
      - migrations

  # Production frontend service
  # frontend-prod:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - NEXTAUTH_URL=https://tag.local
  #     - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
  #     - API_URL=https://tag.local/grpc-api
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD", "wget", "--spider", "http://localhost:3000"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #   depends_on:
  #     - api

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_NODE_ENV=development
      - APP_BASE_URL=${FRONTEND_URL}
      - NEXT_PUBLIC_APP_BASE_URL=${FRONTEND_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_SECRET=${AUTH0_SECRET}
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  envoy:
    image: envoyproxy/envoy:v1.27-latest
    ports:
      - "80:80"
      - "443:443"
      - "9901:9901"
    volumes:
      - ./infra/envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./certs:/certs:ro
    depends_on:
      - api
      - frontend

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - threadmachine:/var/lib/postgresql/data
    container_name: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Combined proto build service
  proto-build:
    build:
      context: .
      dockerfile: Infra/Dockerfiles/Dockerfile-proto-build
    volumes:
      - ./:/app
    container_name: "proto-build"
    restart: "no"

  generate-models:
    build:
      context: .
      dockerfile: Infra/Dockerfiles/Dockerfile-db-models
    depends_on:
      - db
      - migrations
    command: sqlboiler psql --add-global-variants --wipe
    volumes:
      - ./:/app
    container_name: "generate-models"
    restart: "no"
    environment:
      PSQL_DBNAME: ${POSTGRES_DB}
      PSQL_USER: ${POSTGRES_USER}
      PSQL_PASSWORD: ${POSTGRES_PASSWORD}
      PSQL_HOST: db

  minio:
    image: "bitnami/minio:latest"
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_DEFAULT_BUCKETS: local-bucket

volumes:
  threadmachine:
