output   = "pkg/db/models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  host   = "db"
  dbname = "stringart"
  user   = "postgres"
  pass   = "password"
  schema = "public"
  sslmode  = "disable"
  blacklist = ["migrations", "other"]
[aliases]
  tables = "psql"
