output   = "core/db/models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
  host   = "db"
  dbname = "local"
  user   = "local"
  pass   = "local"
  schema = "public"
  sslmode  = "disable"
  blacklist = ["migrations", "other"]

[aliases.tables.medias]
  up_plural     = "Medias"
  up_singular   = "Media"
  down_plural   = "medias"
  down_singular = "media"
