// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/fieldmaskpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *User) Validate() error {
	return nil
}
func (this *CreateUserRequest) Validate() error {
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	return nil
}
func (this *GetUserRequest) Validate() error {
	return nil
}
func (this *UpdateUserRequest) Validate() error {
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	if this.UpdateMask != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdateMask); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdateMask", err)
		}
	}
	return nil
}
func (this *ListUsersRequest) Validate() error {
	return nil
}
func (this *ListUsersResponse) Validate() error {
	for _, item := range this.Users {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Users", err)
			}
		}
	}
	return nil
}
func (this *DeleteUserRequest) Validate() error {
	return nil
}
func (this *CreateSessionRequest) Validate() error {
	return nil
}
func (this *CreateSessionResponse) Validate() error {
	if this.User != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.User); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("User", err)
		}
	}
	if this.AccessTokenExpireTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.AccessTokenExpireTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("AccessTokenExpireTime", err)
		}
	}
	if this.RefreshTokenExpireTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.RefreshTokenExpireTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("RefreshTokenExpireTime", err)
		}
	}
	return nil
}
func (this *RefreshTokenRequest) Validate() error {
	return nil
}
func (this *RefreshTokenResponse) Validate() error {
	if this.AccessTokenExpireTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.AccessTokenExpireTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("AccessTokenExpireTime", err)
		}
	}
	if this.RefreshTokenExpireTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.RefreshTokenExpireTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("RefreshTokenExpireTime", err)
		}
	}
	return nil
}
func (this *DeleteSessionRequest) Validate() error {
	return nil
}
func (this *ResetPasswordRequest) Validate() error {
	return nil
}
func (this *ValidateEmailRequest) Validate() error {
	return nil
}
func (this *SendValidationEmailRequest) Validate() error {
	return nil
}
