# Stage 1: Node.js
FROM node:22.1.0-bullseye-slim

# Set the working directory inside the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y protobuf-compiler make

# Copy the rest of your project files into the container.
COPY . .

# Change to /web directory
WORKDIR /app/web

# Install protoc-gen-ts
RUN npm install -g protoc-gen-ts

# Install protoc-gen-grpc-web
RUN npm install protoc-gen-grpc-web

WORKDIR /app
