// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file art.proto (package pb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { FieldMask, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_field_mask, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_api_field_behavior } from "./google/api/field_behavior_pb";
import { file_google_api_resource } from "./google/api/resource_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file art.proto.
 */
export const file_art: GenFile = /*@__PURE__*/
  fileDesc("CglhcnQucHJvdG8SAnBiIvYBCgNBcnQSKgoEbmFtZRgBIAEoCUIc4kEBA/pBFQoTYXJ0LmV4YW1wbGUuY29tL0FydBITCgV0aXRsZRgCIAEoCUIE4kEBAhIRCglpbWFnZV91cmwYAyABKAkSLQoGYXV0aG9yGAQgASgJQh3iQQED+kEWChRhcnQuZXhhbXBsZS5jb20vVXNlchI1CgtjcmVhdGVfdGltZRgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCBOJBAQMSNQoLdXBkYXRlX3RpbWUYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQgTiQQEDIl0KEENyZWF0ZUFydFJlcXVlc3QSLQoGcGFyZW50GAEgASgJQh3iQQED+kEWChRhcnQuZXhhbXBsZS5jb20vVXNlchIaCgNhcnQYAiABKAsyBy5wYi5BcnRCBOJBAQIiXwoQVXBkYXRlQXJ0UmVxdWVzdBIaCgNhcnQYASABKAsyBy5wYi5BcnRCBOJBAQISLwoLdXBkYXRlX21hc2sYAiABKAsyGi5nb29nbGUucHJvdG9idWYuRmllbGRNYXNrIjsKDUdldEFydFJlcXVlc3QSKgoEbmFtZRgBIAEoCUIc4kEBAvpBFQoTYXJ0LmV4YW1wbGUuY29tL0FydCJnCg9MaXN0QXJ0c1JlcXVlc3QSLQoGcGFyZW50GAEgASgJQh3iQQEC+kEWChRhcnQuZXhhbXBsZS5jb20vVXNlchIRCglwYWdlX3NpemUYAiABKAUSEgoKcGFnZV90b2tlbhgDIAEoBSJCChBMaXN0QXJ0c1Jlc3BvbnNlEhUKBGFydHMYASADKAsyBy5wYi5BcnQSFwoPbmV4dF9wYWdlX3Rva2VuGAIgASgFIjEKEERlbGV0ZUFydFJlcXVlc3QSHQoEbmFtZRgBIAEoCUIP4kEBAvpBCAoGcGIuQXJ0QiRaInRocmVhZC1hcnQtZ2VuZXJhdG9yL2NvcmUvcHJvdG87cGJiBnByb3RvMw", [file_google_protobuf_timestamp, file_google_protobuf_field_mask, file_google_api_field_behavior, file_google_api_resource]);

/**
 * @generated from message pb.Art
 */
export type Art = Message<"pb.Art"> & {
  /**
   * The name of the Art resource.
   * For example: "arts/123"
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Title is the art's title.
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * ImageURL is the art's image URL.
   *
   * @generated from field: string image_url = 3;
   */
  imageUrl: string;

  /**
   * The name of the User resource who is the author of the art.
   * For example: "users/456"
   *
   * @generated from field: string author = 4;
   */
  author: string;

  /**
   * CreatedAt is the art's creation time. Output only.
   *
   * @generated from field: google.protobuf.Timestamp create_time = 5;
   */
  createTime?: Timestamp;

  /**
   * UpdatedAt is the art's last update time.
   *
   * @generated from field: google.protobuf.Timestamp update_time = 6;
   */
  updateTime?: Timestamp;
};

/**
 * Describes the message pb.Art.
 * Use `create(ArtSchema)` to create a new message.
 */
export const ArtSchema: GenMessage<Art> = /*@__PURE__*/
  messageDesc(file_art, 0);

/**
 * @generated from message pb.CreateArtRequest
 */
export type CreateArtRequest = Message<"pb.CreateArtRequest"> & {
  /**
   * The parent which owns the arts.
   * For example: "users/456"
   *
   * @generated from field: string parent = 1;
   */
  parent: string;

  /**
   * The art to create.
   *
   * @generated from field: pb.Art art = 2;
   */
  art?: Art;
};

/**
 * Describes the message pb.CreateArtRequest.
 * Use `create(CreateArtRequestSchema)` to create a new message.
 */
export const CreateArtRequestSchema: GenMessage<CreateArtRequest> = /*@__PURE__*/
  messageDesc(file_art, 1);

/**
 * @generated from message pb.UpdateArtRequest
 */
export type UpdateArtRequest = Message<"pb.UpdateArtRequest"> & {
  /**
   * The Art resource to update.
   *
   * @generated from field: pb.Art art = 1;
   */
  art?: Art;

  /**
   * The update mask applies to the resource.
   *
   * @generated from field: google.protobuf.FieldMask update_mask = 2;
   */
  updateMask?: FieldMask;
};

/**
 * Describes the message pb.UpdateArtRequest.
 * Use `create(UpdateArtRequestSchema)` to create a new message.
 */
export const UpdateArtRequestSchema: GenMessage<UpdateArtRequest> = /*@__PURE__*/
  messageDesc(file_art, 2);

/**
 * @generated from message pb.GetArtRequest
 */
export type GetArtRequest = Message<"pb.GetArtRequest"> & {
  /**
   * The name of the Art resource.
   * For example: "users/{user}/arts/{art}"
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message pb.GetArtRequest.
 * Use `create(GetArtRequestSchema)` to create a new message.
 */
export const GetArtRequestSchema: GenMessage<GetArtRequest> = /*@__PURE__*/
  messageDesc(file_art, 3);

/**
 * @generated from message pb.ListArtsRequest
 */
export type ListArtsRequest = Message<"pb.ListArtsRequest"> & {
  /**
   * The parent which owns the arts.
   * For example: "users/456"
   *
   * @generated from field: string parent = 1;
   */
  parent: string;

  /**
   * The maximum number of arts to return. The service may return fewer than this value.
   *
   * @generated from field: int32 page_size = 2;
   */
  pageSize: number;

  /**
   * A page token, received from a previous `ListArts` call.
   *
   * @generated from field: int32 page_token = 3;
   */
  pageToken: number;
};

/**
 * Describes the message pb.ListArtsRequest.
 * Use `create(ListArtsRequestSchema)` to create a new message.
 */
export const ListArtsRequestSchema: GenMessage<ListArtsRequest> = /*@__PURE__*/
  messageDesc(file_art, 4);

/**
 * @generated from message pb.ListArtsResponse
 */
export type ListArtsResponse = Message<"pb.ListArtsResponse"> & {
  /**
   * The arts returned.
   *
   * @generated from field: repeated pb.Art arts = 1;
   */
  arts: Art[];

  /**
   * A token to retrieve next page of results.
   * Pass this value in ListArtsRequest.page_token field in the subsequent call to `ListArts` method to retrieve the next page of results.
   *
   * @generated from field: int32 next_page_token = 2;
   */
  nextPageToken: number;
};

/**
 * Describes the message pb.ListArtsResponse.
 * Use `create(ListArtsResponseSchema)` to create a new message.
 */
export const ListArtsResponseSchema: GenMessage<ListArtsResponse> = /*@__PURE__*/
  messageDesc(file_art, 5);

/**
 * @generated from message pb.DeleteArtRequest
 */
export type DeleteArtRequest = Message<"pb.DeleteArtRequest"> & {
  /**
   * The name of the Art resource.
   * For example: "arts/123"
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message pb.DeleteArtRequest.
 * Use `create(DeleteArtRequestSchema)` to create a new message.
 */
export const DeleteArtRequestSchema: GenMessage<DeleteArtRequest> = /*@__PURE__*/
  messageDesc(file_art, 6);

