// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts,import_extension=none"
// @generated from file services.proto (package pb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteUserRequest, GetCurrentUserRequest, GetUserRequest, ListUsersRequest, ListUsersResponse, UpdateUserRequest, User } from "./user_pb";
import { Empty, MethodKind } from "@bufbuild/protobuf";
import { Art, Composition, ConfirmArtImageUploadRequest, CreateArtRequest, CreateCompositionRequest, DeleteArtRequest, DeleteCompositionRequest, GetArtRequest, GetArtUploadUrlRequest, GetArtUploadUrlResponse, GetCompositionRequest, ListArtsRequest, ListArtsResponse, ListCompositionsRequest, ListCompositionsResponse, UpdateArtRequest, UpdateCompositionRequest } from "./art_pb";

/**
 * @generated from service pb.ArtGeneratorService
 */
export const ArtGeneratorService = {
  typeName: "pb.ArtGeneratorService",
  methods: {
    /**
     * @generated from rpc pb.ArtGeneratorService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.GetUser
     */
    getUser: {
      name: "GetUser",
      I: GetUserRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.ListUsers
     */
    listUsers: {
      name: "ListUsers",
      I: ListUsersRequest,
      O: ListUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.DeleteUser
     */
    deleteUser: {
      name: "DeleteUser",
      I: DeleteUserRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.GetCurrentUser
     */
    getCurrentUser: {
      name: "GetCurrentUser",
      I: GetCurrentUserRequest,
      O: User,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.CreateArt
     */
    createArt: {
      name: "CreateArt",
      I: CreateArtRequest,
      O: Art,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.GetArt
     */
    getArt: {
      name: "GetArt",
      I: GetArtRequest,
      O: Art,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.UpdateArt
     */
    updateArt: {
      name: "UpdateArt",
      I: UpdateArtRequest,
      O: Art,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.ListArts
     */
    listArts: {
      name: "ListArts",
      I: ListArtsRequest,
      O: ListArtsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.DeleteArt
     */
    deleteArt: {
      name: "DeleteArt",
      I: DeleteArtRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.GetArtUploadUrl
     */
    getArtUploadUrl: {
      name: "GetArtUploadUrl",
      I: GetArtUploadUrlRequest,
      O: GetArtUploadUrlResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.ConfirmArtImageUpload
     */
    confirmArtImageUpload: {
      name: "ConfirmArtImageUpload",
      I: ConfirmArtImageUploadRequest,
      O: Art,
      kind: MethodKind.Unary,
    },
    /**
     * Composition RPCs
     *
     * @generated from rpc pb.ArtGeneratorService.CreateComposition
     */
    createComposition: {
      name: "CreateComposition",
      I: CreateCompositionRequest,
      O: Composition,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.GetComposition
     */
    getComposition: {
      name: "GetComposition",
      I: GetCompositionRequest,
      O: Composition,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.UpdateComposition
     */
    updateComposition: {
      name: "UpdateComposition",
      I: UpdateCompositionRequest,
      O: Composition,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.ListCompositions
     */
    listCompositions: {
      name: "ListCompositions",
      I: ListCompositionsRequest,
      O: ListCompositionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc pb.ArtGeneratorService.DeleteComposition
     */
    deleteComposition: {
      name: "DeleteComposition",
      I: DeleteCompositionRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

