FROM node:22-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application
COPY . .

# Expose the port Next.js runs on
EXPOSE 3000

# Set up the command to run the application
CMD ["npm", "run", "dev"]
